export const carePlanModel = {
  allergies: {
    allergyName: "",
    severity: "",
    dateRecorded: "",
    reaction: "",
    notes: "",
  },
  vaccination: {
    vaccineName: "",
    vaccineType: "",
    administeredAt: "",
    nextDueDate: "",
    batchNumber: "",
    administeredBy: "",
    notes: "",
  },
  surgeries: {
    surgeryName: "",
    surgeryType: "",
    dateOfSurgery: "",
    surgeonName: "",
    postOpCare: "",
    notes: "",
  },
  diagnoses: {
    diagnosisType: "",
    condition: "",
    dateOfDiagnosis: "",
    diagnosisStatus: "",
    symptoms: "",
    notes: "",
  },
  laboratory: {
    testName: "",
    testType: "",
    dateConducted: "",
    conductedBy: "",
    testResult: "",
    notes: "",
  },
  medication: {
    medicationName: "",
    dosage: "",
    frequency: "",
    dateTimeTaken: "",
    startDate: "",
    endDate: "",
    notes: "",
  },
  administrationMedication: {
    name: "",
    dosage: "",
    frequency: "",
    method: "",
    startDate: "",
    endDate: "",
    dateTimeAdministered: "",
    notes: "",
  },
  carePlan: {
    problems: [],
    treatmentPlan: "",
    rehabilitationPlan: "",
    prescribedMedications: "",
    dietaryRecommendations: "",
    ownerInstructions: "",
    emergencyPlan: "",
    followUpDateTime: "",
    notes: "",
  },
};
